In [1]:
import numpy as np

# Array de numpy

In [2]:
npa = np.array(range(10))

In [3]:
npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(npa)

numpy.ndarray

# Ejemplos básicos

In [5]:
a = np.array([1,2,3])

In [16]:
b= np.array([2,4,True])

In [18]:
c = np.array([1,False,"a"])

# Funciones básicas de numpy

In [8]:
np_cero = np.zeros(10)
np_cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [71]:
np_cero_int = np.zeros(10,dtype=int)
np_cero_int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np_ones = np.ones(10)
np_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np_relleno = np.full(10, 256.)

In [14]:
np_relleno

array([256, 256, 256, 256, 256, 256, 256, 256, 256, 256])

In [60]:
# seed=np.random.seed(1)
Np_random_dimensiones = np.random.randint(10,size=(3,4))
Np_random_dimensiones

array([[3, 0, 8, 6],
       [4, 5, 6, 2],
       [5, 7, 8, 4]])

# Dimensiones formas y tamaños de los arrays

In [48]:
np_cero.ndim

1

In [63]:
Np_random_dimensiones.ndim

2

In [65]:
Np_random_dimensiones.shape

(3, 4)

In [66]:
Np_random_dimensiones.size


12

In [78]:
Np_random_dimensiones.dtype

dtype('int32')

# Acceso a los  elementos

In [76]:
Np_random_dimensiones

array([[3, 0, 8, 6],
       [4, 5, 6, 2],
       [5, 7, 8, 4]])

In [94]:
Np_diez_numeros = np.arange(11)
Np_diez_numeros

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
Np_diez_numeros[-1]

10

In [90]:
Np_diez_numeros[1::2]

array([ 2,  4,  6,  8, 10])

In [85]:
Np_random_dimensiones

array([[3, 0, 8, 6],
       [4, 5, 6, 2],
       [5, 7, 8, 4]])

In [84]:
Np_random_dimensiones[2, 1]


7

# Operaciones básicas

In [115]:
Array_aleatorio = np.random.randint(10, size=10)
Array_aleatorio

array([4, 7, 7, 4, 9, 0, 2, 0, 7, 1])

In [127]:

print('suma =',Array_aleatorio.sum())
print('promedio =', Array_aleatorio.mean())
print('Max =',Array_aleatorio.max())
print('std = ',np.std(Array_aleatorio))
print('var =',np.var(Array_aleatorio))
print('mediana =', np.median(Array_aleatorio))

suma = 41
promedio = 4.1
Max = 9
std =  3.1128764832546763
var = 9.690000000000001
mediana = 4.0


In [128]:
A = np.array([7,0,6,7,5])
B = np.array([3,7,9,9,0])

In [130]:
A*B

array([21,  0, 54, 63,  0])

In [131]:
# producto escalar
np.matmul(np.array([1,2,3]),np.array([4,5,6]))

32

In [132]:
np.matmul(A,B)

138

# Reshape, concatenación, splitting


In [98]:
rango = np.arange(1,65)
rango

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [108]:
chess = rango.reshape(8,8)

In [107]:
np.split(rango, [20,40])

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
        38, 39, 40]),
 array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
        58, 59, 60, 61, 62, 63, 64])]

In [114]:
np.split(chess,[3])

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])]

In [111]:
np.hsplit(chess, [3])

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19],
        [25, 26, 27],
        [33, 34, 35],
        [41, 42, 43],
        [49, 50, 51],
        [57, 58, 59]]),
 array([[ 4,  5,  6,  7,  8],
        [12, 13, 14, 15, 16],
        [20, 21, 22, 23, 24],
        [28, 29, 30, 31, 32],
        [36, 37, 38, 39, 40],
        [44, 45, 46, 47, 48],
        [52, 53, 54, 55, 56],
        [60, 61, 62, 63, 64]])]

In [112]:
np.vsplit(chess, [3])

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])]

# Producto escalar

In [46]:
np.matmul(np.array([1,2,3]),np.array([4,5,6]))

32