In [1]:
import numpy as np

In [2]:
z = np.array([1,2,3.])

In [3]:
z

array([1., 2., 3.])

In [5]:
x = np.array(range(3))
x

array([0, 1, 2])

In [6]:
np.concatenate([x,x])

array([0, 1, 2, 0, 1, 2])

In [9]:
np.vstack(x)

array([[0],
       [1],
       [2]])

In [11]:
np.array(range(64)).reshape(8,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])